name: Automatic update

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Send request to server
      run: curl -X POST -F 'secret=${{ secrets.PHP_UPDATE_SECRET }}' -F 'updatedocs=false' https://theultimatefoxos.dev/kerneldoc-update.php