name: Automatic update

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Setup Deno
      # uses: denoland/setup-deno@v1
      uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
      with:
        deno-version: v1.x
    - name: Clone horizon
      run: git clone https://github.com/TheUltimateFoxOS/horizon.git --branch "bring-back-the-docs"
    - name: Build horizon docs
      run: cd horizon; deno run -A tools/doc/main.ts; cp -rv docs ../src/docs
    - name: Build files
      run: node build.js
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        publish_branch: gh-pages
    - name: Send request to server
      run: curl -X POST -F 'secret=${{ secrets.PHP_UPDATE_SECRET }}' -F 'updatedocs=false' https://theultimatefoxos.dev/kerneldoc-update.php
    - name: Tell google to check sitemap
      run: sleep 30 && curl https://www.google.com/ping?sitemap=https://theultimatefoxos.dev/sitemap.xml
