name: Automatic update

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Send request to server
      uses: satak/webrequest-action@master
      with:
        url: https://theultimatefoxos.dev/kerneldoc-update.php
        method: POST
        payload: '{"secret": "${{ secrets.PHP_UPDATE_SECRET }}", "updatedocs": "false"}'
